### ISSUE TITLE
The project does not start

### ISSUE THREAD

**Issue by Kenseori** [SystemXFiles/process-governor#28]
## Describe the bug

PyInstaller\hooks\rthooks\pyi_rth_pkgres.py:37: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
2024-09-29 15:30:50,566 - proc-gov - INFO - Creating backup of the current configuration before migration...
2024-09-29 15:30:50,566 - proc-gov - INFO - [MigrationRules2SplitRulesConfig] Starting migration...
2024-09-29 15:30:50,567 - proc-gov - INFO - [MigrationRules2SplitRulesConfig] Migration completed to version 1.
2024-09-29 15:30:50,567 - proc-gov - INFO - [NewFieldsInRule] Starting migration...
2024-09-29 15:30:50,567 - proc-gov - INFO - [NewFieldsInRule] Migration completed to version 2.
2024-09-29 15:30:50,567 - proc-gov - INFO - [RemoveHighIoPriorityAndLogging] Starting migration...
2024-09-29 15:30:50,567 - proc-gov - INFO - [RemoveHighIoPriorityAndLogging] Migration completed to version 3.
Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File "subprocess.py", line 1597, in _readerthread
  File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
2024-09-29 15:30:53,249 - proc-gov - INFO - Application started
2024-09-29 15:30:53,260 - proc-gov - INFO - Configuration file has been modified. Reloading all rules to apply changes.
Exception in thread Thread-6 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File "subprocess.py", line 1597, in _readerthread
  File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Exception in thread Thread-8 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File "subprocess.py", line 1597, in _readerthread
  File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>

### Steps to reproduce

Launching the program

### Expected behavior

I expected the program to start.

### Environment

- Windows Version: 11
  AMD Ryzen 7 7840H w/ Radeon 780M Graphics       (8 Cores, 16 Threads)

### Additional context

I decided to look for a program to change priorities on github. I really liked this project and the launch consisted of only 4 steps, but for me it failed on the second step

**Comment by SystemXFiles** [comment]
@Kenseori, thank you for reporting the issue!

1. What language is your Windows set to? This could be important as the problem might be related to a non-standard locale or encoding.
2. Could you please attach the log file and configuration file as attachments? Simply copying and pasting the text might not be enough for proper analysis.

**Comment by SystemXFiles** [comment]
@Kenseori Kindly reminder
